# Generated by Django 5.2 on 2025-05-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatecv',
            name='education_levels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candidatecv',
            name='experience',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidatecv',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candidatecv',
            name='tools',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
