# Generated by Django 5.2 on 2025-05-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_candidatecv_education_levels_candidatecv_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='education_levels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='experience',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='tools',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
